---
title: "GSEA on pathways and cytoscape visualisation"
author: "Aishwarya"
date: "2023-03-17"
output: html_document
---

```{r setup, include=FALSE}
if(!"knitr" %in% installed.packages()){
  install.packages("knitr")
}
library(knitr)
knitr:::input_dir()
```

```{r}
##load required packages
if(!require(RCy3)){
  install.packages("Rcy3")
  library(RCy3)}
if(!require(tidyverse)){
  install.packages("tidyverse")
  library(tidyverse)}
if(!require(dplyr)){
  install.packages("dplyr")
  library(dplyr)}
if(!require(msigdbr)) {
  install.packages("msigdbr")
  library(msigdbr) }
if(!require(clusterProfiler)) {
  install.packages("clusterProfiler")
  library(clusterProfiler) }
if(!require(Hmisc)) {
  install.packages("Hmisc")
  library(Hmisc) }
```



```{r cars}
#import data: containing logFC, p-value, adjusted p-value and gene ids. 

psvdvshnl<- read.delim("../psvdvshnl.txt",header=TRUE, row.names = 1)

```



```{r}
##create a genelist for GSEA
#ranking gene on p-value
psvdvshnl$ranking<-psvdvshnl$logFC*-log10(psvdvshnl$P.Value)
#ranking on product of logFC*-log10(adjusted p-value)
psvdvshnl$ranking_alt<-psvdvshnl$logFC*-log10(psvdvshnl$adj.P.Val)

#select the ranking: logFC*-log10(adjusted p-value)
geneList= psvdvshnl[,9]
#add entrex gene id as gene names
names(geneList) = as.character(rownames(psvdvshnl))
#sort on decreasing order
geneList = sort(geneList,decreasing = TRUE)
```



```{r}
#msigdb gene sets

kegg_gene_sets = msigdbr(species = "human", category = "C2", subcategory = "CP:KEGG")
reactome_gene_sets = msigdbr(species = "human", category = "C2", subcategory = "CP:REACTOME")
wikipathways_gene_sets = msigdbr(species = "human", category = "C2", subcategory = "CP:WIKIPATHWAYS")
bp_gene_sets<-msigdbr(species = "human", category = "C5", subcategory = "GO:BP")
```

```{r}
#interchange the column name for bp_gene_sets "gs_description' and gs_name'
gs_name<- bp_gene_sets$gs_description
bp_gene_sets$gs_description<-NULL
names(bp_gene_sets)[names(bp_gene_sets)=="gs_name"]<-"gs_description"
bp_gene_sets$gs_name<-gs_name
```



```{r}
##combine the WikiPathway, Reactome and KEGG gene sets
pathway_gene_sets<-rbind(bp_gene_sets, wikipathways_gene_sets, kegg_gene_sets, reactome_gene_sets)


##process the gene set as the input for the GSEA
pathway_gene_sets<- pathway_gene_sets %>%
     dplyr::select(gs_exact_source, entrez_gene, gs_description, gs_subcat) %>%
    dplyr::rename(ont = gs_exact_source, gene = entrez_gene, description = gs_description, source = gs_subcat )

pathway_gene_sets   


```



```{r}
##GSEA 
pathway_gsea<-GSEA(geneList,
                   TERM2GENE = pathway_gene_sets,
                   maxGSSize = 500,
                   minGSSize = 100,
                   seed = TRUE,
                   by = "fgsea",
                   pAdjustMethod ="fdr",
                   pvalueCutoff = 0.05
  
)
head(pathway_gsea,30)
```



```{r cars}
#import the clusterprofiler enrichment output
pathway_names<-data.frame(pathway_gsea@result[["ID"]])


##create a list including the pathways enriched and their genesets
complete=list()
for (pathways in pathway_names$pathway_gsea.result...ID...){
complete[[pathways]]<-data.frame(genes = pathway_gsea@geneSets[[pathways]],
                                 pathway_id = rep(c(pathways), each = nrow(complete[[pathways]])))
  
}
```
## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
##Create a dataframe with pathways and genesets

pathway_data<-bind_rows(complete)

```


```{r}
##calculate no of genes up and down regulated significantly: up : 1 and down:2 nd unchanged:0
psvdvshnl$names<-rownames(psvdvshnl)
psvdvshnl$condition[psvdvshnl$logFC >= 1 & psvdvshnl$adj.P.Val < 0.05] <- 1
psvdvshnl$condition[psvdvshnl$logFC <= -1 & psvdvshnl$adj.P.Val < 0.05] <- 2
psvdvshnl$condition[is.na(psvdvshnl$condition)]<- 0


##merging the two dataframes based on gene ids
merged_data<-merge(pathway_data, psvdvshnl, by.x = "genes", by.y = "names", all.x = TRUE)

#remove rows of NAs from the data
merged_data<-merged_data[complete.cases(merged_data),]

##create edge table
combined_pathways<-as.data.frame(merged_data[,1:2])
```


```{r}
#counting frequencies
Counting<- data.frame(with(merged_data, unclass(table(pathway_id, condition))))

##renaming the columns
colnames(Counting)<-c("not-changed", "up-sig", "down-sig")
##calculating the total genes in a geneset
Counting$total<-Counting$`not-changed`+Counting$`up-sig`+Counting$`down-sig`
Counting$id<-rownames(Counting)
```

```{r}

##Adding description for the pathway id
pathway_ont<-merge(Counting, pathway_gene_sets[,c(1,3,4)], by.x = "id", by.y = "ont", all.x = TRUE)
pathway_ont<-pathway_ont%>%
  distinct()

##Adding additonal columns
pathway_ont$logFC<-c(rep(c(NA), each = nrow(pathway_ont)))
pathway_ont$AveExpr<-c(rep(c(NA), each = nrow(pathway_ont)))
pathway_ont$t<-c(rep(c(NA), each = nrow(pathway_ont)))
pathway_ont$P.Value<-c(rep(c(NA), each = nrow(pathway_ont)))
pathway_ont$adj.P.Val<-c(rep(c(NA), each = nrow(pathway_ont)))
pathway_ont$B<-c(rep(c(NA), each = nrow(pathway_ont)))
pathway_ont$condition<-c(rep(c(NA), each = nrow(pathway_ont)))
pathway_ont$names<-c(rep(c(NA), each = nrow(pathway_ont)))
pathway_ont$diffexpressed<-c(rep(c(NA), each = nrow(pathway_ont)))
rownames(pathway_ont)<-pathway_ont$id

```

```{r}
##add NES score for pathway
NES_dataframe<-data.frame(id = pathway_gsea@result[["ID"]],
                          NES_score= pathway_gsea@result[["NES"]])
pathway_ont<-merge(pathway_ont, NES_dataframe, by.x="id", by.y="id", all.x=TRUE)
```



```{r}
##Adding additonal columns
psvdvshnl$id <- c(rep(c(NA), each = c(nrow(psvdvshnl))))
psvdvshnl$`up-sig` = c(rep(c(NA), each = c(nrow(psvdvshnl))))
psvdvshnl$`down-sig`<-c(rep(c(NA), each = c(nrow(psvdvshnl))))
psvdvshnl$`not-changed`<-c(rep(c(NA), each = c(nrow(psvdvshnl))))
psvdvshnl$total<-c(rep(c(NA), each = c(nrow(psvdvshnl))))
psvdvshnl$description<-c(rep(c(NA), each = c(nrow(psvdvshnl))))
psvdvshnl$source<-c(rep(c(NA), each = c(nrow(psvdvshnl))))
psvdvshnl$NES_score<-c(rep(c(NA), each = c(nrow(psvdvshnl))))
psvdvshnl$ranking<-NULL
psvdvshnl$ranking_alt<-NULL
```

```{r}
#remove rows of NAs from the data
merged_data<-merged_data[complete.cases(merged_data),]

##create edge table
combined_pathways<-as.data.frame(merged_data[,1:2])

##node table
gene_id<-data.frame(id=unique(merged_data$genes))
gene_id$group<-c(replicate(nrow(gene_id), "Gene"))
pathway_id<-data.frame(id=pathway_ont$id,
                       group=pathway_ont$source)
node_table<-data.frame(id = rbind(gene_id, pathway_id))
colnames(node_table)<-c("id", "group")

```


```{r}
#combine the pathway and gene table
cytoscape_table<-rbind(psvdvshnl, pathway_ont)
```



```{r}
##calculating mutual nodes 
list_df<-split(combined_pathways, combined_pathways$pathway_id)
##split into multiple dataframes
list2env(list_df, envir= .GlobalEnv)
```

```{r}
##mutual nodes


#pathway_ids<-pathway_names$pathway_gsea.result...ID...

pathway_enrich<-as_tibble(pathway_id$id)





rows= c(1:nrow(pathway_id))
times = nrow(pathway_id)
pathway_ids<-as.data.frame(pathway_id[rep(rows, times),])
pathway_ids$pathway_id_second<-pathway_enrich[rep(seq_len(nrow(pathway_enrich)), each=nrow(pathway_id)),]
pathway_ids<-as.data.frame(pathway_ids)

for (i in 1:nrow(pathway_ids)){
  

pathway_ids$mutual_nodes[i]<-length(intersect(list_df[[pathway_ids[i,1]]][["genes"]], list_df[[unlist(pathway_ids[i,3])]][["genes"]]));
  
}

colnames(pathway_ids)<-c("source", "database", "target", "mutual_nodes")

```


```{r}
##make the edge table
pathway_ids<-subset(pathway_ids, mutual_nodes>0)
pathway_ids<-pathway_ids[-c(which(pathway_ids$source==pathway_ids$target)),]

```

```{r}
##adding an edge if the mutual nodes is above 50
pathway_ids$condition[pathway_ids$mutual_nodes> 50] <- 1
pathway_ids$condition[pathway_ids$mutual_nodes< 50] <- 0

pathway_ids<-subset(pathway_ids, condition ==1)

```


```{r}
##nes score condition positive or negative
pathway_ont$NES_score_condition[pathway_ont$NES_score > 0] <- "positive"
pathway_ont$NES_score_condition[pathway_ont$NES_score < 0] <- "negative"



```

```{r}
cytoscapePing()
if("cytargetlinker" %in% commandsHelp("")) print("Success: the CyTargetLinker app is installed") else print("Warning: CyTargetLinker app is not installed. Please install the CyTargetLinker app before proceeding.")
```

```{r}
##Node table: Gene ID (Entrez) and Pathway Ids( KEGG, Reactome and WikiPathways)

pathway_gene_nodes <- data.frame(id=pathway_id$id,
                        group= pathway_id$group,
                        stringsAsFactors = FALSE)


# Edges : Gene-pathway associations
pathway_gene_edges <- data.frame(source=pathway_ids$source,
                        target=pathway_ids$target,
                        weight = pathway_ids$mutual_nodes,
                        interaction=replicate(nrow(pathway_ids), "contains"),
                        stringsAsFactors = FALSE)

colnames(pathway_gene_edges)<-c("source", "target", "weight", "interaction" )
##create network in Cytoscape
createNetworkFromDataFrames(pathway_gene_nodes, pathway_gene_edges, title="GSEA pathway nodes cluster", collection="GSEA")
```


```{r}
cytoscape_table$description<-tolower(cytoscape_table$description)
cytoscape_table$description<-capitalize(cytoscape_table$description)
```

```{r}
pathway_ont$description_new<-gsub("^.*?_","_", pathway_ont$description)
pathway_ont$description_new<-gsub("_", " ", pathway_ont$description_new)
pathway_ont$description_new<-tolower(pathway_ont$description_new)
pathway_ont$description_new<-capitalize(pathway_ont$description_new)
#pathway_ont$NES_score<-abs(pathway_ont$NES_score)
```



```{r}
##load node table data 
#loadTableData(cytoscape_table)
rownames(pathway_ont)<-pathway_ont$id
loadTableData(pathway_ont)
#write.table(NES_dataframe, "nes_data.txt", na ="", row.names=FALSE,  sep='\t', quote=FALSE)
```


```{r}
rownames(pathway_id)<-pathway_id$id
loadTableData(pathway_id)
```




```{r}
##set the node shape 
getNodeShapes()   # diamond, ellipse, trapezoid, triangle, etc.
    column <- 'group'
    values <- c('CP:KEGG', 'CP:REACTOME', 'CP:WIKIPATHWAYS', 'GO:BP')
    shapes <- c( 'ELLIPSE' , 'ELLIPSE', 'ELLIPSE', 'ELLIPSE')
    setNodeShapeMapping(column, values, shapes)
```

```{r}
##Adding the pie chart to pathway nodes to visualise the down-regulated, not -changed and the up-regulated genes.
setNodeCustomPieChart(c("down.sig","not.changed","up.sig"), colors = c('#334CFF', '#FFFFFF', '#FD5903') )

lockNodeDimensions(TRUE)
```


```{r}
##set the node size
size<-c(100,100,100,100)
setNodeSizeMapping('group', mapping.type = "d", values, size)
```


```{r}
#set the node label: only set for the pathway nodes
setNodeLabelMapping("description_new")

#set the node position
setNodeCustomPosition(nodeAnchor = "C", graphicAnchor = "C", justification = "c")

#set the node label font size
setNodeFontSizeDefault(20)

#set the font style of the node label
setNodeFontFaceDefault("Arial,Rounded,Bold,45")
```

```{r}
#set the node border width
border_width=c(20,20,20,20, 20)
setNodeBorderWidthMapping('group', mapping.type = "d", values, border_width)
```


```{r}
#set the node border color: for visualising the pathway databases
border_color=c("#FD5903", "#0026D3" )
setNodeBorderColorMapping('NES_score_condition', mapping.type = "d", values, border_color)
```



```{r}
#set the edge color
setEdgeColorDefault("#D7DBDD")
```
```{r}
deleteDuplicateEdges()
```






Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
